// Generated by CoffeeScript 1.7.1
(function() {
  App.register("{{id}}", function(params, scope, widgets) {
    return {
      getData: function() {},
      submit: function() {}
    };
  });

}).call(this);

//# sourceMappingURL=form.map
